[package]
name = "sm64js-db"
version = "0.1.0"
authors = ["Mario Reder <mreder1289@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
chrono = "0.4"
diesel = { version = "1", features = ["chrono", "postgres", "r2d2"] }
serde = "1"
