on: 
  push:
    paths:
      - "crates/**/*"
      - ".github/workflows/test.yml"
  pull_request:
    paths:
      - "crates/**/*"
      - ".github/workflows/test.yml"

name: Rust Server Test

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RUST_BACKTRACE: full

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions-rs/toolchain@v1
        name: Install Toolchain
        with:
          profile: minimal
          toolchain: nightly-2022-01-06
          override: true
          components: rustfmt, clippy

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/cargo@v1
        name: Check
        with:
          command: check

      # TODO needs tests
      # - uses: actions-rs/cargo@v1
      #   name: Test
      #   with:
      #     command: test

      - uses: actions-rs/cargo@v1
        name: Fmt
        with:
          command: fmt
          args: -- --check

      - uses: actions-rs/cargo@v1
        name: Clippy
        with:
          command: clippy
          args: -- -D warnings
